### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by stefnotch** [jarbun/downline#10]
Would you mind publishing [a new release](https://github.com/jarbun/downline/releases)?

It would be great to have, especially now that https://github.com/jarbun/downline/issues/7 has been fixed.

**Comment by jarbun** [comment]
New release [1.3.1](https://github.com/jarbun/downline/releases/tag/v1.3.1)
Apologies for taking so long

**Comment by stefnotch** [comment]
🎉 Thank you!
