### ISSUE TITLE
Developer Instructions - Clarification

### ISSUE THREAD

**Issue by PAEz** [jarbun/downline#11]
Sorry if this is a dumb question but I couldnt figure out from your instructions on how to run the dev.
First try got me a blank app.
After a bunch of poking it seemed to want the file served from a local server on port 5500.
Port 5500 came up as vscode liver server alot in google.
Tried that and lovely, I can edit without having to restart the app each time, nice.
No big deal, just want to make sure Im getting this right.  Want to fork it and add a couple of things I want.  I want a context menu for paste (got that done) and a way to cast to kodi (simple stuff, done it before).

PS
While Im here just wanna say I love this app.  It works, looks good and the code is lovely.  Ive always thought of vue as "too much" but this makes it look good, very easy to follow.

**Comment by stefnotch** [comment]
> First try got me a blank app.

That's odd. Are you sure that you added the platform specific versions of youtube-dl and ffmpeg in the [correct folder](https://github.com/jarbun/downline/blob/a19c9785cbf1ce22a0eaaed07734b0f2d4fc9fa6/src/ytdl.js#L29)?
```
resources
├ ffmpeg
│ └ ffmpeg.exe
└ youtube-dl
  └ youtube-dl.exe
```

**Comment by PAEz** [comment]
npm run dev
Will start the app in dev mode in which there is code in main.js to expect it served from "http://127.0.0.1:5500/src/index.html" but what starts that server?
If this is just some electron thing I dont know sorry, new to it.

**Comment by jarbun** [comment]
> After a bunch of poking it seemed to want the file served from a local server on port 5500.
> Port 5500 came up as vscode liver server alot in google.
> No big deal, just want to make sure Im getting this right.

Yes, and I use the ```vscode live server``` extension on my end, so you've got it right. It is entirely my fault for not being clear on how to set up the server. I'll add some additional information in the README.

I think it would be better to include a package like ```http-server``` as a development dependency, so you won't have to worry about setting up the server manually. I'm currently working on a complete re-design and re-write, for downline 2.x, so I'll include stuff like this that makes development easier.

> It works, looks good and the code is lovely.

Thanks a lot. I made this without much planning, so most of the code looks ugly to me. That's part of the reason for the re-write. The new version will use Vue Components which should make the code easier to read, maintain and update.
