### ISSUE TITLE
Getting source link from items in list

### ISSUE THREAD

**Issue by Rahmanism** [jarbun/downline#14]
It's not an issue. It's a suggestion.
It would bu nice that user could open (or copy the link of) an item from list. Let's say I'm downloading something from YouTube. I  want to open it in YouTube by clicking on it in the list or getting the link by right-clicking on it.
Thank you.

**Comment by balkarjun** [comment]
That's a good suggestion. I'll add a context menu option to copy the item's link, in v2.x that I'm currently working on.

**Comment by balkarjun** [comment]
Feature available in v2.0.0-alpha.1. Just right click on an item in the list, and a context menu will show up, with the option to copy the link.
