### ISSUE TITLE
Fails to register YouTube video

### ISSUE THREAD

**Issue by stefnotch** [jarbun/downline#5]
I've noticed that a few videos in an [anime playlist](https://www.youtube.com/playlist?list=PLIFiiT-qVg9KpOPetG0wuXmySktRoRVG7) cannot be downloaded.

One example of such a video is
https://www.youtube.com/watch?v=MOrwW6avyGU

When copy-pasting the URL into Downline, it will load for a while, but fail to add the video to the list of videos. As such, you can't download it

**Comment by jarbun** [comment]
I am able to load the video, from the link you provided, on my end. 

#### Are you using the latest version of Downline (v1.3.0)?
If you are and it still does not work, go to the **About** page, and **update youtube-dl**. This can take a while, and should say **updated successfully** when it's done. Restart Downline and try to load the video again.

#### If the update fails or takes too long
The update does not work for Linux AppImages, and it sometimes takes forever when Downline is installed using the setup on Windows. In this case, I recommend using the portable version for [Linux](https://github.com/jarbun/downline/releases/download/v1.3.0/downline-1.3.0-portable-linux.tar.xz) or [Windows](https://github.com/jarbun/downline/releases/download/v1.3.0/downline-1.3.0-portable-windows.7z) instead, and then follow the steps to update youtube-dl.

If even this fails to fix the issue (which is unlikely), go to the installation directory of Downline. There should be a folder named **resources** in which you'll find the youtube-dl executable (Windows) or python file (Linux and MacOS). Delete that file and replace it with the latest version for your platform, which can be obtained [here](https://ytdl-org.github.io/youtube-dl/download.html).

Please reply if this fixed (or failed to solve) the issue. Thanks.

**Comment by stefnotch** [comment]
Thank you very much for your quick response. I'm already using the latest version of Downline (v1.3.0), however it seems that my youtube-dl version was outdated. **It now works perfectly.**

I clicked on the update button and was faced with this error message.
![image](https://user-images.githubusercontent.com/10220080/55648394-7f354880-57e0-11e9-83c8-be8ab73ae2c2.png)

However, after waiting a while, it simply disappeared and everything was fine.
![image](https://user-images.githubusercontent.com/10220080/55648406-878d8380-57e0-11e9-9f54-bce482c8c7f2.png)
(I suppose that's a minor visual bug. Updating youtube-dl worked perfectly, even though initially an error message appeared. I'll report it if it happens again.)

**Comment by jarbun** [comment]
Great! 
And yes, I can confirm the bug. Has happened to me while updating as well.
I'll try fixing it soon.

**Comment by tudza** [comment]
I switched to the portable Windows version and did the YouTube-DL operation. Still no change.

I looked in the expected folder and found the youtube-dl.exe and another called youtube-del.exe.new.  I renamed the new one to match the old file and then everything works as expected.
