### ISSUE TITLE
Youtube-dl doesn't update on mac

### ISSUE THREAD

**Issue by KostasKostogloy** [jarbun/downline#7]
I downloaded and run the 1.3.0 version on mac and youtube detection was not working. I tried updating Youtube-dl from the About page with no success.

I then proceeded to manually replace the youtube-dl file with the one that I had installed locally and my problem was solved.

So the problem here is that:
1. Downline ships with an outdated youtube-dl version
2. Youtube-dl update seems broken

**Comment by stefnotch** [comment]
I can also confirm this issue on Windows

**Comment by stefnotch** [comment]
Relevant source: https://github.com/jarbun/downline/blob/4fc7738b5e002008f79c0bdeec96851685214636/src/ytdl.js#L213
